### ISSUE TITLE
Total time on watch is incorrect after app crash on watch

### ISSUE THREAD

**Issue by KaptenJansson** [jonasoreland/runnerup#175]
Version: 1.39 beta

Steps to reproduce:
1. Start a run/bike activity
2. Pause the activity on the watch
3. Not quite sure but I believe I dismissed the app by swiping to the right
4. App on watch crashed
5. Started the app on the watch and the 52.23 time seen in screenshot appeared while you can see the real time in the screenshot of the app on the phone 19.18 minutes.

[Screenshot of app on phone](https://drive.google.com/file/d/0B71pLQBYIPv-dHZaTmFWTHJ3am8/view?usp=sharing)
[Screenshot of app on watch](https://drive.google.com/file/d/0B71pLQBYIPv-VmllY3VDYl9SQmM/view?usp=sharing)

**Comment by jonasoreland** [comment]
Hi there,
thx for great bug report! brilliant!!
1) the time is incorrect after start/stop of wear app is already fixed in https://github.com/jonasoreland/runnerup/commit/568c4ed788c9018226d10cd921eb6a11aa0410b7.
a new version will be published "shortly" (maybe this weekend)

2) regarding step 4, the "app on watch crashed"
if you swiped it to the right, it not crashing, but rather being stopped.
or ?? wdyt ?

/Jonas

**Comment by KaptenJansson** [comment]
Good stuff;)

Swiping to the right is a standard gesture for dismissing apps on wear, is it wise to change that?

**Comment by KaptenJansson** [comment]
I also noticed that when starting a new activity, the time from the previous activity is displayed for a few seconds before 00:00 is displayed. Will 568c4ed fix this as well?

**Comment by jonasoreland** [comment]
yes

/Jonas

**Comment by jonasoreland** [comment]
fixed ?
