### ISSUE TITLE
Work without Google Play Services?

### ISSUE THREAD

**Issue by jas4711** [jonasoreland/runnerup#20]
This app seems to be exactly what I have been looking for -- and I would like to install it on my Samsung S3 which is running Replicany without any GAPPS stuff.  However the app seems to depend on Google Play Services, which is a no-no for me.  Would it be possible to relax this requirement so that it is an optional dependency?  What does the app use Google Play Services for?  Thanks in advance.

Btw, someone mentioned your app on the fdroid forum as well: https://f-droid.org/forums/topic/runnerup-an-open-source-run-tracker-for-android/

/Simon

**Comment by netmackan** [comment]
I'm currently looking a bit on how to do different builds with and without Google services.
Have I understood correctly that the two product flavors "froyo" and "latest" are their so the app can be built both with and without Wear support?

**Comment by nebmo** [comment]
Yes you are correct (froyo does not support wear)

**Comment by netmackan** [comment]
I'm trying to figure out how this build process with different source folders work but I think there is something strange with my set up. 

Is it expected that out of the 3 source folders ("src", "froyo/java" and "latest/java") there is only packages for src and froyo visible in the IDE?

See the packages "org.runnerup" and "org.runnerup (froyo)" in the screenshot below:

![runnerup-android-studio](https://cloud.githubusercontent.com/assets/48208/6986199/351ee764-da3b-11e4-93cf-00099cc7dd67.png)

**Comment by netmackan** [comment]
Never mind my last question.
I now found the Build Variants tab (lower left in the screenshot) where I can change the active variant to "latest" and the source package then changes.

**Comment by netmackan** [comment]
I am experimenting with introduced a flavor dimension "map", with the "gmap" and "nomap" flavors (later an osmap one could potentially be added for #21). Currently the gmap flavors works to build but not yet the nomap ones as those requires some refactorings but that is just Java so shouldn't be a big problem.

The biggest issue at the moment though, is that all though both froyoGmap and latestGmap builds fine, Android Studio shows compilation errors in the editor. It seem it does not recognize the dependencies properly. Maybe the IDE does not support them being added within if-statements in build.gradle (?)

My branch is available here if anyone wants to have a look and has some ideas:
https://github.com/netmackan/runnerup/tree/optional-gapps-build-1

I also have a branch where I simply patched away anything by Google here to later see what refactorings would be needed:
https://github.com/netmackan/runnerup/tree/no-gapps-hack-1

**Comment by jonasoreland** [comment]
Hi,

i haven't checked your branch (yet)...but only want to provide some context.
i think detecting presense of gapps in the app and choose map provider
based which are present is fine.

however, the people at f-droid want to be able to *build* RunnerUp without
gapps...and this is where the flavors would come into play.

/Jonas

**Comment by bagage** [comment]
@netmackan : what is the current status of this issue? This gradle flavor feature might do the trick, but what about Eclipse/ant? Will we definitively drop its support?
@jonasoreland : is gmaps mandatory? Would not it be easier to drop gmaps support and instead fully use openstreetmap? Or is there any advantage to use gmaps that I do not see other than being already implemented :)?

**Comment by jonasoreland** [comment]
i don't know of any major advantage except being implemented...

**Comment by dalb8** [comment]
There isn't that much advantage to using GMS: see microg/android_packages_apps_UnifiedNlp/#36

**Comment by netmackan** [comment]
@bagage The status from my side is that I have created a branch (https://github.com/netmackan/runnerup/tree/optional-gapps-build-1) where I have implemented the idea of having new build flavor dimension for the type of map implementation with different source folders for the respective one. This would allow us to then refactor the code to still have the gmaps support while also being able to build without any map as a first step to get the builds on f-droid. Then later one could also add support for other map implementation and then either continue with the different versions or decide to switch to use only a non-gmaps one.

All though building the different versions of the app seems to work fine switching between the different flavors in the Android Studio IDE was not always reliable. I will try again and see if the issue is still present but as I remembered it, after switching from one flavor to an other the dependencies of the previous was (sometimes?) still in affect which for instance could show compilation errors in the source code editor at the same time building still worked...

I haven't considered Eclipse, mainly because I don't use it myself and as the README suggested the build wasn't working anyway. For NetBeans IDE there is a nice Android/Gradle plugin that can be used. Maybe there eventually (or already is) something similar for Eclipse?

**Comment by netmackan** [comment]
Upgraded Android Studio to 1.2.2 but still it seems the compile time dependencies was not picked up by the editor. It could be something other that is wrong with the Gradle parts as well.

Unless somebody else sees what I am doing wrong, maybe switching directly to OSM would be easier.

**Comment by bagage** [comment]
@netmackan OK thanks for the status point.I thing I will directly drop google maps support and we will only use OSM provider in the future.

**Comment by patcon** [comment]
Hey all, this is all really exciting developments, but would it be sensible to move discussion of FOSS replacement into https://github.com/jonasoreland/runnerup/issues/21, and leave this for discussion of stripping enough to get things building on F-Droid? Just to keep issues focussed :)
