### ISSUE TITLE
Convert uploaders to use org.apache.http

### ISSUE THREAD

**Issue by jonasoreland** [jonasoreland/runnerup#206]
when I started writing uploaders, I had never done any REST call in my life.
hence I wanted to know excatly how things work. now i do.
i think converting uploaders to use the org.apache.http classes means that
it would be significantly less code and make it more robust too.

**Comment by paradix** [comment]
Based on this http://developer.android.com/reference/org/apache/http/package-summary.html the apache client is deprecated in the android api.

It seems that the apache implementation would be nice to use but you would probably need to use this one https://code.google.com/p/httpclientandroidlib/ as the one android supplies is a bit old and not updated since version 4.0beta2.

**Comment by paradix** [comment]
Or just use https://hc.apache.org/httpcomponents-client-4.3.x/android-port.html

**Comment by jonasoreland** [comment]
or just stick to "pure" android,
and try to create methods/classes usable by all syncronizers...

i didn't know about the deprecation (puh...)

i'm closing this instead

**Comment by paradix** [comment]
Hah, thats a pity. Using apache was so nice and easy :)

**Comment by jonasoreland** [comment]
yea...

and to me it sounds like a really poor decision to add the apache thing...
only to then deprecate it.
that has to make lots of developers grumpy...

well, shit happens

/Jonas

**Comment by nebmo** [comment]
@daverix seems to like:
http://square.github.io/retrofit/
