### ISSUE TITLE
Transifex ressources are not up to date

### ISSUE THREAD

**Issue by ixeft** [jonasoreland/runnerup#267]
Hello,
There is some new string on the english cues.xml file which are not translatable into transifex (example : per hour)

can you upload the new files ? (if you put me as maintainer, I will be pleased to do it :) )

@bagage @jonasoreland

**Comment by jonasoreland** [comment]
done.
sorry :(

/Jonas

**Comment by jonasoreland** [comment]
how do I make you maintainer ??

**Comment by bagage** [comment]
I am not totally confident about making someone maintainer; since you can overwrite base resources files, you must really know what you are doing: only @jonasoreland/master branch has to be put on Transifex, which is generally quite up-to-date with Transifex @ixeft is not it?

If you know what being an English maintainer implies (eg. not screwing original files), then we can add you [there ("Team manager settings" I guess?)](https://www.transifex.com/organization/runner-up/teams/).

**Comment by ixeft** [comment]
Hello,
I proposed my help mainly in case you had no time to do it,
But, the problem was solve very quickly, so, no need to change what is working ;)

Thank you for the update !
