### ISSUE TITLE
Failed to make release with Mapbox

### ISSUE THREAD

**Issue by jonasoreland** [jonasoreland/runnerup#317]
1) First proguard failed to compile
I added
+-dontwarn okio.**
+-dontwarn com.vividsolutions.jts.awt.**
+-dontwarn android.support.**
+-dontwarn com.squareup.okhttp.**
+-keep class com.squareup.okhttp.** { *; }
+-keep interface com.squareup.okhttp.** { *; }

2) now it seems that the map doesnt work with the new release.
Unclear why...

**Comment by bagage** [comment]
Even if a never used proguard i'll take a look at it until end of week...

**Comment by jonasoreland** [comment]
thx!

**Comment by bagage** [comment]
First thing first, proguard is total sh!t. (seriously, this tool...).
Secondly, this has been broken since #312 (commit 17d01ab) , release or not. Maybe @daverix knows what's going on there?

**Comment by bagage** [comment]
OK fix is easy, i'll do a PR.

**Comment by jonasoreland** [comment]
thx!

**Comment by bagage** [comment]
Concerning the new release, could we just remove the "experimental features" settings which enables extra sports, and just use them always?
Any uploader which does not support them yet will uploads them as "Other" sport, except for Facebook which will drop them (because other not supported). In any case there will still be uploaded to all trackers, right?

**Comment by jonasoreland** [comment]
Hmm...that sounds reasonable.
