### ISSUE TITLE
[Feature request]: Export functionality

### ISSUE THREAD

**Issue by matthiasbeyer** [jonasoreland/runnerup#363]
Hi,

I'd really love an export funcitonality in this app, where I can export my data as CSV or JSON (or XML). Please implement such a thing.

---

Thanks for developing this app. I just found it in f-droid and I will definitively use this app, it really looks awesome, though it has a rather complex UI and I guess I have to play around a bit until I understand everything!

**Comment by dom134** [comment]
Hello there

This is a great app, which connects seamlessly with my bluetooth heart strap and records everything that I need it to.  I agree with Matthias; I would like to be able to keep a gpx file privately, without sending it to Runkeeper, Garmin or some other proprietary fitness tracking agency.

Otherwise, this app is great, please keep up the great work!
Dom

**Comment by gerhardol** [comment]
For export, see Android >=5 limitation
https://github.com/jonasoreland/runnerup/issues/298

**Comment by jonasoreland** [comment]
i think this is solved now.
1) you can export single activities via the share menu item
2) you can export automatically via the File-exporter (which is in next release).

**Comment by gerhardol** [comment]
To save as a file you can use Dropbox, Gmail or Solid Explorer
ES Explorer and others does not work . The way RunnerUp shares files is compatible with Android 7, it may be that the other file sharing has to be updated so no deep effort there.
