### ISSUE TITLE
Waiting for location.. Forever..

### ISSUE THREAD

**Issue by rupeshsasne** [jonasoreland/runnerup#376]
I build the app and installed on real device running on android 5.1.. this app is not getting location but other apps like nike+, RunKeeper are getting exact location data.. Is it a known bug?

From where should I start debugging it?

**Comment by Gittino** [comment]
Hi, 
I had a similar problem on my device, but I don't know if it is exactly the same issue.
My problem occurs because when I run I'm totally offline (no data connection) when runnerup starts the GPS it enables it in High Accuracy mode (Get info from GPS, Wifi, Mobile networks etc.) . 
I noticed that if I switch the GPS to Device Only mode (Get info only from GPS) after a while it gets the correct location.

**Comment by gerhardol** [comment]
Similar to #578, closing as duplicate
