### ISSUE TITLE
Connecting to Garmin Connect not works

### ISSUE THREAD

**Issue by filin2009** [jonasoreland/runnerup#580]
When trying to enter login and password, form is closing and nothing happening. 
Workout is not uploading into Garmin Connect.
Endomondo, Strava and Runkeeper is ok.

**Comment by gerhardol** [comment]
Garmin has changed the license agreement, there is a cost of $5000 to connect.
Garmin should be removed or hidden in the app.

There is a not updated status page here:
https://github.com/jonasoreland/runnerup/blob/master/SYNCHRONIZERS.md

**Comment by gerhardol** [comment]
Garmin will be hidden in the GUI (both upload and workout) when #590 is merged

**Comment by johnsie** [comment]
How long a period does that 5000 cover and for how many users/requests?

**Comment by gerhardol** [comment]
I not know, this fee was reported by other users at that time and may be incorrect or changed since then. 
There is no public ingo, the details are something you get to know when your business is accepted by garmin (no fee for that). I applied once while asking for open source conditions and was denied without a further explanation. similar terms for .fit access.
