### ISSUE TITLE
global timing/distance invalid

### ISSUE THREAD

**Issue by moobyfr** [jonasoreland/runnerup#632]
Having made a half marathon, I saw that runnerup was displaying 1h32 and 20.3km instead of 1h38/21.3km. I use autolap on 1000m, current version from f-droid
The application only display 21 splits instead of 22. I've exported the track as tcx, and it seems that Laps are incorrectly computed.
 Every Lap have a TotalTimeSeconds and DistanceMeters probably correct (In my case ~280s/~1000m), but there is too much Trackpoint into each Lap. This can be probably the source of the problem as global distance/time is the sum of all Lap entries

As example, First lap:

```
</Lap>
        <TotalTimeSeconds>284</TotalTimeSeconds>
        <DistanceMeters>1001.60895</DistanceMeters>

... 
            <Trackpoint> (last one)
            <DistanceMeters>1114.9258</DistanceMeters>
</Lap>
```

The TCX can be downloaded here: http://manu.agat.net/RunnerUp_0032-2.tcx

**Comment by gerhardol** [comment]
Do you have autopause enabled?
What recording options are used?
(Track is both sparse sampled which could be OK if configured so, otherwise the GPS quality seem to be low.)
The track seem like auto pause is enabled. Pauses are _not_ implemented in .tcx exports. Maybe handled in RunKeeper and Endomondo, try exporting there to confirm auto pauses.

The default is to enable autopause. This unfortunate as auto pause is sensitive for GPS quality, it is quite aggressive. I have suggested that auto pause at least is turned off by default, possibly that the setting is is less aggressive too.

**Comment by gerhardol** [comment]
The core problem here is Autopause. That feature works on some phones in some situations. Unfortunately autopause has been enabled by default. (Changed for new installations for next release, #673).
So the lap summaries are correct.
You can see pauses on the map, uploading to Endomondo and Runkeeper should also exclude pauses - not what you want to see here though.

However, pauses are not visible in the tcx/gpx and the services that sync with tcx/gpx like Strava. There is actually no universal standard for pauses in these files. (There was a definition for tcx, but Garmin removed the documentation some years ago and implementing that may break services.)

The distance in the tcx should not have been increased over pauses, but almost all importers ignore that information anyway.

I cannot see an universal algorithm for reliable auto-pause so the solution is to not use that functionality.
It would be a little hard to remove the functionality completely as it may  work for some users, but maybe the setting should be deactivated when upgrading to next version.
