### ISSUE TITLE
Activities no longer upload to Runalyze.com

### ISSUE THREAD

**Issue by craftyguy** [jonasoreland/runnerup#638]
It seems like some recent changes to runalyze have broken the upload feature of this app. The 'https://runalyze.com/activity/add' page does not seem to exist anymore.

Here's the error in logcat when I try to upload an activity:

```
01-28 21:26:56.768 11609 14572 E Runalyze: Error importing into Runalyze: 
01-28 21:26:56.768 11609 14572 E Runalyze: java.io.FileNotFoundException: https://runalyze.com/activity/add
01-28 21:26:56.768 11609 14572 E Runalyze:      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:251)
01-28 21:26:56.768 11609 14572 E Runalyze:      at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
01-28 21:26:56.768 11609 14572 E Runalyze:      at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(Unknown Source:0)
01-28 21:26:56.768 11609 14572 E Runalyze:      at org.runnerup.export.RunalyzeSynchronizer.upload(RunalyzeSynchronizer.java:524)
01-28 21:26:56.768 11609 14572 E Runalyze:      at org.runnerup.export.SyncManager$11.doInBackground(SyncManager.java:644)
01-28 21:26:56.768 11609 14572 E Runalyze:      at org.runnerup.export.SyncManager$11.doInBackground(SyncManager.java:639)
01-28 21:26:56.768 11609 14572 E Runalyze:      at android.os.AsyncTask$2.call(AsyncTask.java:333)
01-28 21:26:56.768 11609 14572 E Runalyze:      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
01-28 21:26:56.768 11609 14572 E Runalyze:      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
01-28 21:26:56.768 11609 14572 E Runalyze:      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
01-28 21:26:56.768 11609 14572 E Runalyze:      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
01-28 21:26:56.768 11609 14572 E Runalyze:      at java.lang.Thread.run(Thread.java:764)

```

**Comment by craftyguy** [comment]
Ah. I was trying to determine what exactly changed server-side to break this, but I was not able to :(

**Comment by iggar** [comment]
Oh, I've noticed that as well. I'd love to have a look at that and try and fix it. I should have some time tonight and over this weekend. I can see there's a form to manually upload data, as well as the file picker button. So I'm sure it won't be a big deal to fix that.

**Comment by mark74** [comment]
I'm facing the very same problem in the last period.
If someone is able to solve it I'd be really happy 👍

**Comment by twitwi** [comment]
I'm sharing my exploration in case it helps someone fix it (I cannot rebuilt the application right now).

I have the same problem.
However, I see no exception: it seems the page `https://runalyze.com/activity/add` exists (again?).
From what I could get from the logs, it seems the server returns no error (code 200) but the code expects a particular message there:

https://github.com/jonasoreland/runnerup/blob/6b383f3ad11c0f51ec8ff2097528c642f4d22184/app/src/org/runnerup/export/RunalyzeSynchronizer.java#L534

NB: When manually uploading via `https://runalyze.com/activity/upload` it seems there is a POST on `https://runalyze.com/activity/upload` (to actually upload the gpx) and when we validate, there is another POST on `https://runalyze.com/activity/new` with a whole list of parameters in the request. This last request returns some html containing the message that is expect in the line I linked above.

There also seem to still be the `/activity/add` API in the runnerup codebase: https://github.com/Runalyze/Runalyze/blob/1ac99a417f22f01312b687ce3075c5330ccefecb/src/CoreBundle/Controller/Activity/CreateController.php#L35
which forwards to `/activity/new`: https://github.com/Runalyze/Runalyze/blob/1ac99a417f22f01312b687ce3075c5330ccefecb/src/CoreBundle/Controller/Activity/CreateController.php#L235 
(it is probably not the issue here, but maybe runnerup should prefer "new" directly because "add" depends on the configuration of runalyze). 

I tried to understand what changed between version 4.2 and 4.3 of runalyze but did not find a obvious cause for the problem (I don't know symfony). Here is the diff, I'd say: https://github.com/Runalyze/Runalyze/compare/activityImportQueue...7927b08dbb3f88d22d5596288bc54f480705c4c7#diff-455af8e9d14e711948850407d073f8d7

**Comment by twitwi** [comment]
There seem to have been a big refactoring commit: https://github.com/Runalyze/Runalyze/commit/1ac99a417f22f01312b687ce3075c5330ccefecb#diff-92a7639eabc74abdc26615cce639ee33

which has moved and rewritten `/activity/add` from `src/CoreBundle/Controller/ActivityController.php` to `src/CoreBundle/Controller/Activity/CreateController.php`

**Comment by mipapo** [comment]
Only valid for runalyze.com:
```
Before I start with some details:
1. This is just a workaround. We don't guarantee that this works perfectly.
2. This workaround will be shut down after we implemented the API and authorization via oauth2. (~1-2 months after production)

I tested this url with some files. And so far it works fine. You are only able to push one file per request. You cannot set anything else like sport type or whatever. The sport is guessed by the file informations and the fall back is the main sport of the user.

You can POST the file to https://runalyze.com/_internal/upload/direct
"file" is the post key. See a POSTMAN example attached
```

**Comment by craftyguy** [comment]
@mipapo when you tested this, did you modify runnerup or did you use something like curl to send the file manually?

**Comment by mipapo** [comment]
@craftyguy  Tested it with curl and Postman

**Comment by craftyguy** [comment]
@mipapo

That's excellent news!! Thank you!

Do you have any documentation on what the API supports, how to use it, etc? I tries searching but came up with nothing.

**Comment by mipapo** [comment]
@craftyguy Please get in contact directly with me. We don't have an open documentation, because the API is currently limited to push activities to Runalyze.

**Comment by craftyguy** [comment]
I took a stab at implementing support for the new runalyze API, PR is #652. I was able to upload both a running and biking event successfully.

@jonasoreland if you choose to merge this PR, you'll need to request a client ID / secret to use with runnerup from @mipapo

**Comment by mipapo** [comment]
just FYI @craftyguy wrote an mail and will not work longer on this issue and the pr #652 because RUNALYZE is not open source anymore.

**Comment by Marx2** [comment]
Strava and Endomondo is not open source either. Yet we maintain
synchronisation with them.

niedz., 27.05.2018, 17:56 użytkownik Michael Pohl <notifications@github.com>
napisał:

**Comment by craftyguy** [comment]
I'm not the maintainer for this app (RunnerUp), and I had no part in adding support for those services, but I refuse to spend my time trying to add support for walled gardens like Strava, Endomondo, and runalyze.

**Comment by gerhardol** [comment]
@craftyguy is it OK to use your work so far?

There are other issues to be solved: handle the expiring token and handle key (the second part must be handled by @jonasoreland or by someone forking the app).

**Comment by craftyguy** [comment]
@gerhardol yea, you can use my PR, I won't close it.

Yea, there definitely needs to be a mechanism for handling expired tokens since runalyze expires their tokens after some time.
