### ISSUE TITLE
WGS Geoid correction in GPX files

### ISSUE THREAD

**Issue by ericbechet** [jonasoreland/runnerup#653]
The WGS corrected altitude is only written to TCX files, not in GPX files. If that is an issue or a feature is not perfectly clear to me...

when I upload back the gpx file in an external editor (e.g. qmapshack or gpxsee), the TCX shows corrected altitudes (which match available DEM models), wherease the GPX file just stores the raw data from the gps sensor (uncorrected). In addition, the GPX file seem more complete (the above softwares do not interpret the extended data in the TCX file correcty, but this is another issue)

For this, the last option in the "recording" section (Enregistrement in French) of the parameters is set on. If set to off, no elevation is recorded in the GPX file...

**Comment by gerhardol** [comment]
The error is that elevation is not written to GPX files. This will be corrected.

Some further explanation:
GeoID correction is applied when recording and is not really involved here. Elevation can be obtained from barometers and elevation be corrected for other reasons to so it is not just GeoID that changes elevation.
 
With "Accuracy extension" the original GPS elevation is stored in the database too (Accuracy but not other data like speed, bearing and no of sats are stored).
* If you disable the option after recording, there is no difference in the output.
* If you record with Off and export with On you will still get the Accuracy additional data.

The issue was that if not additional data was enabled (or no additional data recorded), the check if there were elevation was incorrect. As RU requires GPS, this should never even happen...
