### ISSUE TITLE
Export- Import function does not work

### ISSUE THREAD

**Issue by harryhackebeil** [jonasoreland/runnerup#783]
I tried to export my settings with options and export to SD and to import them to another phone and it did not work in total.

I exported with version 1.58 on LG G4 with android 6.0 (Kernel 3.10.84, Softwareversion V20m-262-02) and got a file named runnerup.db.export with about 46 MB.
I import to version 1.58 on Opeplus 6 with android 9 (Kernel 4.9.106-perf+ with OxygeneOS 9.0.5) and do not get any error message, but there are no runs in my history and no workouts I designed by myself. The only thing that worked is, that it activated my nike+ account on the new phone.
Additionally loggin in into my Garmin Connect account doesn't work either on bothe phones (I found this might be a function to transfer the selfmade workouts).

**Comment by gerhardol** [comment]
Import database is already fixed in master and will be included in next build. (That functionality has been broken since I have used RU, starting with intent should work tough.)

Garmin Connect and many other services do no longer work when sites have been shutdown or sites limited the APIs. Garmin for instance charges $5000 to allow connections. It should be possible to sync using Tapiriik. 
See the wiki for details, also for workouts.
https://github.com/jonasoreland/runnerup/wiki/Synchronization-with-external-providers

**Comment by gerhardol** [comment]
Resolved in #775

**Comment by harryhackebeil** [comment]
Thank you!
