### ISSUE TITLE
Long term future planing

### ISSUE THREAD

**Issue by vojtechhuser** [jonasoreland/runnerup#912]
Some issues mention problems with coordination with development.

With all due credits for creation and many years of work, should the project be open somehow to more developers ?

**Comment by Marx2** [comment]
It's already open, everybody can join. There's no long term plans, because
there are only 2-3 developers max, and they do it after hours.

wt., 28 kwi 2020, 02:20 użytkownik Vojtech Huser <notifications@github.com>
napisał:

**Comment by gerhardol** [comment]
The primary question if this project should be forked on Play or not.
I do not get any response from Jonas why no new versions are uploaded to Play. 
I do not feel that I should make that change, as I am not using the app more as a logger occasionally. Someone with greater interest should be maintaining and adding more features in the long run. I have spent considerable time on the app and do not plan to abandon it, but most time tend to be spent on behind the scenes changes like updating the internals so the app can potentially be updated in Play.

This project needs more contributors. I have merge rights to this repo, but if Play is forked, the upstream repo should be changed too, preferably an organisation repo rather than a private one.

**Comment by Marx2** [comment]
What organisation could it be? I'd like to have it stay open source
forever. Which organisation can guarantee it? For sure not Cheetah like
which packs tons of ads, nor Microsoft, which would probably kill app soon
(like Wunderlist).

I saw soon there will be limits for GPS usage in Android. We probably will
need to apply for permission to use it. It would be good to have some
strong organisation behind.

Do you think Apache organisation could be interested in such an app? Any
ideas?

wt., 28 kwi 2020, 10:13 użytkownik Gerhard Olsson <notifications@github.com>
napisał:

**Comment by gerhardol** [comment]
> limits for GPS usage in Android

There are limits for usage in the background, but not for foreground apps, with notifications.
Many devices kill apps anyway, see https://dontkillmyapp.com/

I was just thinking that there should be a GitHub and Play account not related to a person directly.
I doubt that any bigger FOSS organisations will pick up a runners app.
Obviously, there has to be someone in control behind, it will not work well if everyone can merge and publish...

**Comment by gerhardol** [comment]
2.0.6.4 updated to Play, I got access

**Comment by gerhardol** [comment]
2.1.0.0 is released to Production
